### ISSUE TITLE
Error Block-Scoped declarations

### ISSUE THREAD

**Issue by dennyexalto** [athombv/nl.eneco.toon#2]
After installing the app is directly crashes: (Currently working on 0.8.39)

Stack trace:

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/drivers/toon/driver.js:1:74)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

**Comment by RobinBol** [comment]
App is not released, nor finished.
